# -*- coding: utf-8 -*-
"""Assignment1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16aKN1WFrn8P8TiOLHtpVJjAV2znvfumK
"""

# preamble to be able to run notebooks in Jupyter and Colab
try:
    from google.colab import drive
    import sys
    
    drive.mount('/content/drive')
    notes_home = "/content/drive/My Drive/csc310/"
    user_home = "/content/drive/My Drive/"
    
    sys.path.insert(1,notes_home) # let the notebook access the notes folder

except ModuleNotFoundError:
    notes_home = "" # running native Jupyter environment -- notes home is the same as the notebook
    user_home = ""  # under Jupyter we assume the user directory is the same as the notebook

import pandas

"""This data set is about a large group of animals characterized based on many traits from do they have hair? Fins? Feathers? Etc.[zoo.csv](https://drive.google.com/file/d/1Zkz3-gTIEHMO-1Fo7VT76uUNAqaAefGF/view?usp=sharing). Taken from the UCI data repository.


"""

zoo_df = pandas.read_csv(user_home+"zoo.csv")

zoo_df

"""Columns: 18

Rows: 101

All the data is in numerical data but the Booleans are categorical.
All columns have information.

Categorical:

Hair: no  
Feathers: no 

Eggs: yes  
Milk: no

Airborne: no

Aquatic: no     
Predator: yes

Toothed: yes     
Backbone: yes      
Breathers: yes     
Venomous: no     
Fins: no    
Tail: yes        
Domestic: no     
Catsize: no

Numerical:

Legs:  Min: 0	Max: 8	Mean: 2.8 or 3 legs	
Type: Min: 1	Max: 7	Mean: 2.8 or 3

"""

zoo_df['catsize'].mode()

zoo_df['type'].min()

zoo_df['type'].max()

zoo_df['type'].mean()

zoo_df.hist()

beaver = pandas.read_csv(user_home+"beaver.csv")

"""This data set is about the temperature of beavers over 2 days when they are active and inactive.[beaver.csv](https://drive.google.com/file/d/14jaR5yDieYarW4CODi9iV4rgYNdNHfgv/view?usp=sharing) Taken from R Datasets."""

beaver

"""Rows: 100

Columns: 5

All the data is numerical data apart from the boolean row which is active.

The first column "Unnamed" has no data. 

**Day:**

Min: 307

Max: 308

Mean: 307

**Time** 

Min:0

Max: 2350

Mean:1446.2

**Temp**

Min: 36.58

Max: 38.35

Mean: 36.58

**Active**

Mode: Yes or 1


"""

beaver['day'].min()

beaver['time'].mean()

beaver['temp'].max()

beaver['activ'].mode()

beaver.hist()