# -*- coding: utf-8 -*-
"""PlottingPractice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cxBOiov4vxgLfvOVy6LV_7kWJggFsL2L
"""

# preamble to be able to run notebooks in Jupyter and Colab
try:
    from google.colab import drive
    import sys
    
    drive.mount('/content/drive')
    notes_home = "/content/drive/My Drive/csc310/"
    user_home = "/content/drive/My Drive/"
    
    sys.path.insert(1,notes_home) # let the notebook access the notes folder

except ModuleNotFoundError:
    notes_home = "" # running native Jupyter environment -- notes home is the same as the notebook
    user_home = ""  # under Jupyter we assume the user directory is the same as the notebook

import numpy as np
import pandas as pd

from pandas.plotting import andrews_curves
data = pd.read_csv(notes_home+'iris.csv')
pd.plotting.andrews_curves(data, 'Species')